language: python
python:
  - "3.6"

cache: pip

branches:
  only:
  - master

install:
  - pip install -r requirements.txt
  - python setup.py -q install

script:
  - flake8 --ignore=E501 ansible_runner_service.py runner-service/
  - cd tests && python -m unittest test_*.py
