language: python
python:
  - "3.6"

cache: pip

branches:
  only:
  - master

install:
  - pip install -r requirements.txt
  - python setup.py -q install
  - pip install coverage
  - pip install codecov

script:
  - flake8 --ignore=E501 ansible-runner-service.py runner-service/
  - python -m unittest tests/test_*.py
  - coverage run --source=runner_service -m unittest tests/test_*.py

after_success:
- codecov
