language: python
python:
  - "3.6"

addons:
  apt:
    packages:
      - openssh-server

cache: pip

branches:
  only:
  - master

install:
  - pip install -r requirements.txt
  - python setup.py -q install

script:
  - flake8 --ignore=E501 ansible_runner_service.py runner-service/
  - cd tests && python -v -m unittest test_*.py

after_script:
  - ls -al ~/.ssh
  - cat ~/.ssh/authorized_keys
